env:
  node: true
  commonjs: true
  browser: true
  es6: true
ignorePatterns:
  - '**/dist'
extends:
  - 'plugin:prettier/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
