trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: build
  displayName: Build Node Package
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
    displayName: Install Node.js

  - task: YarnInstaller@3
    inputs:
      versionSpec: 1.x
    displayName: Install Yarn

  - script: |
      yarn
      yarn test --ci
    displayName: Run Tests

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/test_results.xml'
      testRunTitle: Jest Tests

- job: release
  displayName: Release Packages
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
    displayName: Install Node.js

  - task: YarnInstaller@3
    inputs:
      versionSpec: 1.x
    displayName: Install Yarn

  - script: |
      yarn
      yarn release
      git config --global user.email $GH_EMAIL
      git config --global user.name $GH_USERNAME
      git push --tags
    displayName: Release
    env:
      GH_USERNAME: $(GH.Username)
      GH_EMAIL: $(GH.Email)
      GH_TOKEN: $(GH.Token)
      NPM_TOKEN: $(NPM.Token)
