trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: build
  displayName: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
    displayName: Install Node.js

  - script: |
      npm ci
    displayName: Install Packages

  - script: |
      npm run test --ci
    displayName: Run Tests

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '**/test_results.xml'
      testRunTitle: Jest Tests

- job: release
  displayName: Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
    displayName: Install Node.js

  - script: |
      git remote set-url origin https://$GH_USERNAME:$GH_TOKEN@github.com/johnnyhuy/ggsmark.git
      git config --global user.email $GH_EMAIL
      git config --global user.name $GH_USERNAME
      npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      npm ci
      npm run release
    displayName: Node Packages
    env:
      GH_USERNAME: $(GH.Username)
      GH_EMAIL: $(GH.Email)
      GH_TOKEN: $(GH.Token)
      NPM_TOKEN: $(NPM.Token)
      
  - task: GitHubRelease@1
    displayName: GitHub
    inputs:
      gitHubConnection: johnnyhuy-github
      repositoryName: $(Build.Repository.Name)
      action: create
      target: $(Build.SourceVersion)
      tagSource: gitTag
      changeLogCompareToRelease: lastFullRelease
      changeLogType: commitBased
